spring:
  application:
    name: transaction-listener
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: ****
    username: ****
    password: ****

transaction.kafka:
  consumer:
    bootstrapServers: 40.69.78.245:19092
    topic: transactions
    groupId: cashback

transaction.sign: rozovskaja

transaction.rest:
  card: http://****/card-service/api/v1/card/
  client: http://****/client-service/api/v1/client/
  loyalty: http://****/loyalty-service/api/v1/program/
  notification: http://****/notification-service/api/v2/client/